
qodana-python:
  image:
    name: jetbrains/qodana-python
    entrypoint: ['']
  script:
      - qodana --save-report --results-dir=$CI_PROJECT_DIR/qodana
         --report-dir=$CI_PROJECT_DIR/qodana/report
  variables:
      QODANA_TOKEN: $qodana_token
      QODANA_REMOTE_URL: git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git
      QODANA_BRANCH: $CI_COMMIT_BRANCH
      QODANA_REVISION: $CI_COMMIT_SHA
      QODANA_JOB_URL: $CI_JOB_URL
  artifacts:
      paths:
         - qodana
